### ISSUE TITLE
Commentaires code

### ISSUE THREAD

**Issue by mounieju** [PolytechLyon/isi3-tp1-graph-jolivet-mounier#1]
Peut-on supprimer tous les commentaires qui sont inutiles car les méthodes parlent d'elles-même pour pouvoir aérer le code ?

**Comment by Slashgear** [comment]
Oui,

Attention votre UML de classe pour l'adapter n'est pas un UML de classe valide. (Je ne vois pas la composition)

https://fr.wikipedia.org/wiki/Diagramme_de_classes

**Comment by mounieju** [comment]
D'accord, merci on va modifier ça tout de suite ;)
