### ISSUE TITLE
Question 4 - Utilisation d'un autre design pattern

### ISSUE THREAD

**Issue by mounieju** [PolytechLyon/isi3-tp1-graph-jolivet-mounier#2]
Je voulais savoir si on pouvait appliquer le pattern Strategy dans cette situation car on a plusieurs algos qui diffèrent forcément par leur comportement, mais qui font tous les deux un parcours avec Iterator. 
Après j'ai l'impression que ce design pattern ne s'utilise que lorsque le client décide de l'implémentation à utiliser lors de l'exécution, du coup je suis un peu confuse..

**Comment by Slashgear** [comment]
Oui ! 👍
