### ISSUE TITLE
CodeReview

### ISSUE THREAD

**Issue by mounieju** [PolytechLyon/isi3-tp1-graph-jolivet-mounier#3]
Malheureusement, nous n'avons pas trop réussi à mettre en place le pattern Strategy, du coup on a préféré laisser une version certes, non-optimisée, mais plus propre et qui fonctionne. 
Pardon pour le codereview un peu tard, nous voulions faire le maximum pour l'optimisation..

**Comment by Slashgear** [comment]
Ok, si vous trouvez l'idée, n'hésitez pas à me ping.

**Comment by mounieju** [comment]
On a réussi à créer une classe qui implémente les méthodes next et hasNext d'Iterator, et que selon le fils (Birth ou Depth) choisi, le prochain noeud que l'on va visité sera définit par la classe fils (le premier élément de la liste si c'est Birth, le dernier de la liste sinon). 

Est-ce qu'on modifie notre rapport?

**Comment by Slashgear** [comment]
![bravo](https://media.giphy.com/media/l9Tllo1thElT5gvVOU/giphy.gif)

Non c'est bon on passe à la suite
